name: C++ Random Docker CI/CD Pipeline

# 1. Trigger: Ejecuta solo cuando se hace push al main
on:
  push:
    branches: [ main ]

# 2. Jobs: Tareas del pipeline
jobs:
  build_and_push_image:
    runs-on: ubuntu-latest
    steps:
      # Paso 1: Sacar el código del repo
      - name: Checkout Repository Code
        uses: actions/checkout@v4

      # Paso 2: Logear al Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME -u ipv1412 }}
          password: ${{ secrets.DOCKER_TOKEN dckr_pat_FilK0s5w0bCArhIkXbyBa-2oYzU}}

      # Paso 3: Crear y subir la imagen de Docker
      - name: Build and Push C++ Docker Image RANDOM
        uses: docker/build-push-action@v5
        with:
          context: .      
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/random-app:latest

      # Paso 4: Confirmación del despliegue
      - name: Deployment Confirmation
        run: |
          echo "Successfully built and pushed the image to Docker Hub!"
          echo "Image: ${{ secrets.DOCKER_USERNAME }}/random-app:latest"
